//
// This file was generated by tool, do NOT make change by hand.
//

#include "cef_externs.h"

#ifdef DYNAMIC_CEF
#include "include/cef_version.h"
#include "include/capi/cef_app_capi.h"
#include "include/capi/cef_browser_capi.h"
#include "include/capi/cef_command_line_capi.h"
#include "include/capi/cef_cookie_capi.h"
#include "include/capi/cef_crash_util_capi.h"
#include "include/capi/cef_drag_data_capi.h"
#include "include/capi/cef_file_util_capi.h"
#include "include/capi/cef_image_capi.h"
#include "include/capi/cef_menu_model_capi.h"
#include "include/capi/cef_origin_whitelist_capi.h"
#include "include/capi/cef_parser_capi.h"
#include "include/capi/cef_path_util_capi.h"
#include "include/capi/cef_print_settings_capi.h"
#include "include/capi/cef_process_message_capi.h"
#include "include/capi/cef_process_util_capi.h"
#include "include/capi/cef_request_capi.h"
#include "include/capi/cef_request_context_capi.h"
#include "include/capi/cef_resource_bundle_capi.h"
#include "include/capi/cef_response_capi.h"
#include "include/capi/cef_scheme_capi.h"
#include "include/capi/cef_server_capi.h"
#include "include/capi/cef_ssl_info_capi.h"
#include "include/capi/cef_stream_capi.h"
#include "include/capi/cef_task_capi.h"
#include "include/capi/cef_thread_capi.h"
#include "include/capi/cef_trace_capi.h"
#include "include/capi/cef_urlrequest_capi.h"
#include "include/capi/cef_v8_capi.h"
#include "include/capi/cef_values_capi.h"
#include "include/capi/cef_waitable_event_capi.h"
#include "include/capi/cef_web_plugin_capi.h"
#include "include/capi/cef_xml_reader_capi.h"
#include "include/capi/cef_zip_reader_capi.h"
#include "include/capi/test/cef_test_helpers_capi.h"
#include "include/capi/test/cef_translator_test_capi.h"
#include "include/capi/views/cef_browser_view_capi.h"
#include "include/capi/views/cef_display_capi.h"
#include "include/capi/views/cef_label_button_capi.h"
#include "include/capi/views/cef_menu_button_capi.h"
#include "include/capi/views/cef_panel_capi.h"
#include "include/capi/views/cef_scroll_view_capi.h"
#include "include/capi/views/cef_textfield_capi.h"
#include "include/capi/views/cef_window_capi.h"
#include "include/internal/cef_logging_internal.h"
#include "include/internal/cef_string_list.h"
#include "include/internal/cef_string_map.h"
#include "include/internal/cef_string_multimap.h"
#include "include/internal/cef_string_types.h"
#include "include/internal/cef_thread_internal.h"
#include "include/internal/cef_time.h"
#include "include/internal/cef_trace_event_internal.h"

cef_version_info_t cef_version_info = NULL;
cef_api_hash_t cef_api_hash = NULL;
cef_execute_process_t cef_execute_process = NULL;
cef_initialize_t cef_initialize = NULL;
cef_shutdown_t cef_shutdown = NULL;
cef_do_message_loop_work_t cef_do_message_loop_work = NULL;
cef_run_message_loop_t cef_run_message_loop = NULL;
cef_quit_message_loop_t cef_quit_message_loop = NULL;
cef_set_osmodal_loop_t cef_set_osmodal_loop = NULL;
cef_enable_highdpi_support_t cef_enable_highdpi_support = NULL;
cef_browser_host_create_browser_t cef_browser_host_create_browser = NULL;
cef_browser_host_create_browser_sync_t cef_browser_host_create_browser_sync = NULL;
cef_command_line_create_t cef_command_line_create = NULL;
cef_command_line_get_global_t cef_command_line_get_global = NULL;
cef_cookie_manager_get_global_manager_t cef_cookie_manager_get_global_manager = NULL;
cef_cookie_manager_get_blocking_manager_t cef_cookie_manager_get_blocking_manager = NULL;
cef_cookie_manager_create_manager_t cef_cookie_manager_create_manager = NULL;
cef_crash_reporting_enabled_t cef_crash_reporting_enabled = NULL;
cef_set_crash_key_value_t cef_set_crash_key_value = NULL;
cef_drag_data_create_t cef_drag_data_create = NULL;
cef_create_directory_t cef_create_directory = NULL;
cef_get_temp_directory_t cef_get_temp_directory = NULL;
cef_create_new_temp_directory_t cef_create_new_temp_directory = NULL;
cef_create_temp_directory_in_directory_t cef_create_temp_directory_in_directory = NULL;
cef_directory_exists_t cef_directory_exists = NULL;
cef_delete_file_t cef_delete_file = NULL;
cef_zip_directory_t cef_zip_directory = NULL;
cef_load_crlsets_file_t cef_load_crlsets_file = NULL;
cef_image_create_t cef_image_create = NULL;
cef_menu_model_create_t cef_menu_model_create = NULL;
cef_add_cross_origin_whitelist_entry_t cef_add_cross_origin_whitelist_entry = NULL;
cef_remove_cross_origin_whitelist_entry_t cef_remove_cross_origin_whitelist_entry = NULL;
cef_clear_cross_origin_whitelist_t cef_clear_cross_origin_whitelist = NULL;
cef_parse_url_t cef_parse_url = NULL;
cef_create_url_t cef_create_url = NULL;
cef_format_url_for_security_display_t cef_format_url_for_security_display = NULL;
cef_get_mime_type_t cef_get_mime_type = NULL;
cef_get_extensions_for_mime_type_t cef_get_extensions_for_mime_type = NULL;
cef_base64encode_t cef_base64encode = NULL;
cef_base64decode_t cef_base64decode = NULL;
cef_uriencode_t cef_uriencode = NULL;
cef_uridecode_t cef_uridecode = NULL;
cef_parse_json_t cef_parse_json = NULL;
cef_parse_jsonand_return_error_t cef_parse_jsonand_return_error = NULL;
cef_write_json_t cef_write_json = NULL;
cef_get_path_t cef_get_path = NULL;
cef_print_settings_create_t cef_print_settings_create = NULL;
cef_process_message_create_t cef_process_message_create = NULL;
cef_launch_process_t cef_launch_process = NULL;
cef_request_create_t cef_request_create = NULL;
cef_post_data_create_t cef_post_data_create = NULL;
cef_post_data_element_create_t cef_post_data_element_create = NULL;
cef_request_context_get_global_context_t cef_request_context_get_global_context = NULL;
cef_request_context_create_context_t cef_request_context_create_context = NULL;
cef_create_context_shared_t cef_create_context_shared = NULL;
cef_resource_bundle_get_global_t cef_resource_bundle_get_global = NULL;
cef_response_create_t cef_response_create = NULL;
cef_register_scheme_handler_factory_t cef_register_scheme_handler_factory = NULL;
cef_clear_scheme_handler_factories_t cef_clear_scheme_handler_factories = NULL;
cef_server_create_t cef_server_create = NULL;
cef_is_cert_status_error_t cef_is_cert_status_error = NULL;
cef_is_cert_status_minor_error_t cef_is_cert_status_minor_error = NULL;
cef_stream_reader_create_for_file_t cef_stream_reader_create_for_file = NULL;
cef_stream_reader_create_for_data_t cef_stream_reader_create_for_data = NULL;
cef_stream_reader_create_for_handler_t cef_stream_reader_create_for_handler = NULL;
cef_stream_writer_create_for_file_t cef_stream_writer_create_for_file = NULL;
cef_stream_writer_create_for_handler_t cef_stream_writer_create_for_handler = NULL;
cef_task_runner_get_for_current_thread_t cef_task_runner_get_for_current_thread = NULL;
cef_task_runner_get_for_thread_t cef_task_runner_get_for_thread = NULL;
cef_currently_on_t cef_currently_on = NULL;
cef_post_task_t cef_post_task = NULL;
cef_post_delayed_task_t cef_post_delayed_task = NULL;
cef_thread_create_t cef_thread_create = NULL;
cef_begin_tracing_t cef_begin_tracing = NULL;
cef_end_tracing_t cef_end_tracing = NULL;
cef_now_from_system_trace_time_t cef_now_from_system_trace_time = NULL;
cef_urlrequest_create_t cef_urlrequest_create = NULL;
cef_v8context_get_current_context_t cef_v8context_get_current_context = NULL;
cef_v8context_get_entered_context_t cef_v8context_get_entered_context = NULL;
cef_v8context_in_context_t cef_v8context_in_context = NULL;
cef_v8value_create_undefined_t cef_v8value_create_undefined = NULL;
cef_v8value_create_null_t cef_v8value_create_null = NULL;
cef_v8value_create_bool_t cef_v8value_create_bool = NULL;
cef_v8value_create_int_t cef_v8value_create_int = NULL;
cef_v8value_create_uint_t cef_v8value_create_uint = NULL;
cef_v8value_create_double_t cef_v8value_create_double = NULL;
cef_v8value_create_date_t cef_v8value_create_date = NULL;
cef_v8value_create_string_t cef_v8value_create_string = NULL;
cef_v8value_create_object_t cef_v8value_create_object = NULL;
cef_v8value_create_array_t cef_v8value_create_array = NULL;
cef_v8value_create_array_buffer_t cef_v8value_create_array_buffer = NULL;
cef_v8value_create_function_t cef_v8value_create_function = NULL;
cef_v8stack_trace_get_current_t cef_v8stack_trace_get_current = NULL;
cef_register_extension_t cef_register_extension = NULL;
cef_value_create_t cef_value_create = NULL;
cef_binary_value_create_t cef_binary_value_create = NULL;
cef_dictionary_value_create_t cef_dictionary_value_create = NULL;
cef_list_value_create_t cef_list_value_create = NULL;
cef_waitable_event_create_t cef_waitable_event_create = NULL;
cef_visit_web_plugin_info_t cef_visit_web_plugin_info = NULL;
cef_refresh_web_plugins_t cef_refresh_web_plugins = NULL;
cef_unregister_internal_web_plugin_t cef_unregister_internal_web_plugin = NULL;
cef_register_web_plugin_crash_t cef_register_web_plugin_crash = NULL;
cef_is_web_plugin_unstable_t cef_is_web_plugin_unstable = NULL;
cef_register_widevine_cdm_t cef_register_widevine_cdm = NULL;
cef_xml_reader_create_t cef_xml_reader_create = NULL;
cef_zip_reader_create_t cef_zip_reader_create = NULL;
cef_execute_java_script_with_user_gesture_for_tests_t cef_execute_java_script_with_user_gesture_for_tests = NULL;
cef_translator_test_create_t cef_translator_test_create = NULL;
cef_translator_test_ref_ptr_library_create_t cef_translator_test_ref_ptr_library_create = NULL;
cef_translator_test_ref_ptr_library_child_create_t cef_translator_test_ref_ptr_library_child_create = NULL;
cef_translator_test_ref_ptr_library_child_child_create_t cef_translator_test_ref_ptr_library_child_child_create = NULL;
cef_translator_test_scoped_library_create_t cef_translator_test_scoped_library_create = NULL;
cef_translator_test_scoped_library_child_create_t cef_translator_test_scoped_library_child_create = NULL;
cef_translator_test_scoped_library_child_child_create_t cef_translator_test_scoped_library_child_child_create = NULL;
cef_browser_view_create_t cef_browser_view_create = NULL;
cef_browser_view_get_for_browser_t cef_browser_view_get_for_browser = NULL;
cef_display_get_primary_t cef_display_get_primary = NULL;
cef_display_get_nearest_point_t cef_display_get_nearest_point = NULL;
cef_display_get_matching_bounds_t cef_display_get_matching_bounds = NULL;
cef_display_get_count_t cef_display_get_count = NULL;
cef_display_get_alls_t cef_display_get_alls = NULL;
cef_label_button_create_t cef_label_button_create = NULL;
cef_menu_button_create_t cef_menu_button_create = NULL;
cef_panel_create_t cef_panel_create = NULL;
cef_scroll_view_create_t cef_scroll_view_create = NULL;
cef_textfield_create_t cef_textfield_create = NULL;
cef_window_create_top_level_t cef_window_create_top_level = NULL;
cef_get_min_log_level_t cef_get_min_log_level = NULL;
cef_get_vlog_level_t cef_get_vlog_level = NULL;
cef_log_t cef_log = NULL;
cef_string_list_alloc_t cef_string_list_alloc = NULL;
cef_string_list_size_t cef_string_list_size = NULL;
cef_string_list_value_t cef_string_list_value = NULL;
cef_string_list_append_t cef_string_list_append = NULL;
cef_string_list_clear_t cef_string_list_clear = NULL;
cef_string_list_free_t cef_string_list_free = NULL;
cef_string_list_copy_t cef_string_list_copy = NULL;
cef_string_map_alloc_t cef_string_map_alloc = NULL;
cef_string_map_size_t cef_string_map_size = NULL;
cef_string_map_find_t cef_string_map_find = NULL;
cef_string_map_key_t cef_string_map_key = NULL;
cef_string_map_value_t cef_string_map_value = NULL;
cef_string_map_append_t cef_string_map_append = NULL;
cef_string_map_clear_t cef_string_map_clear = NULL;
cef_string_map_free_t cef_string_map_free = NULL;
cef_string_multimap_alloc_t cef_string_multimap_alloc = NULL;
cef_string_multimap_size_t cef_string_multimap_size = NULL;
cef_string_multimap_find_count_t cef_string_multimap_find_count = NULL;
cef_string_multimap_enumerate_t cef_string_multimap_enumerate = NULL;
cef_string_multimap_key_t cef_string_multimap_key = NULL;
cef_string_multimap_value_t cef_string_multimap_value = NULL;
cef_string_multimap_append_t cef_string_multimap_append = NULL;
cef_string_multimap_clear_t cef_string_multimap_clear = NULL;
cef_string_multimap_free_t cef_string_multimap_free = NULL;
cef_string_wide_set_t cef_string_wide_set = NULL;
cef_string_utf8_set_t cef_string_utf8_set = NULL;
cef_string_utf16_set_t cef_string_utf16_set = NULL;
cef_string_wide_clear_t cef_string_wide_clear = NULL;
cef_string_utf8_clear_t cef_string_utf8_clear = NULL;
cef_string_utf16_clear_t cef_string_utf16_clear = NULL;
cef_string_wide_cmp_t cef_string_wide_cmp = NULL;
cef_string_utf8_cmp_t cef_string_utf8_cmp = NULL;
cef_string_utf16_cmp_t cef_string_utf16_cmp = NULL;
cef_string_wide_to_utf8_t cef_string_wide_to_utf8 = NULL;
cef_string_utf8_to_wide_t cef_string_utf8_to_wide = NULL;
cef_string_wide_to_utf16_t cef_string_wide_to_utf16 = NULL;
cef_string_utf16_to_wide_t cef_string_utf16_to_wide = NULL;
cef_string_utf8_to_utf16_t cef_string_utf8_to_utf16 = NULL;
cef_string_utf16_to_utf8_t cef_string_utf16_to_utf8 = NULL;
cef_string_ascii_to_wide_t cef_string_ascii_to_wide = NULL;
cef_string_ascii_to_utf16_t cef_string_ascii_to_utf16 = NULL;
cef_string_userfree_wide_alloc_t cef_string_userfree_wide_alloc = NULL;
cef_string_userfree_utf8_alloc_t cef_string_userfree_utf8_alloc = NULL;
cef_string_userfree_utf16_alloc_t cef_string_userfree_utf16_alloc = NULL;
cef_string_userfree_wide_free_t cef_string_userfree_wide_free = NULL;
cef_string_userfree_utf8_free_t cef_string_userfree_utf8_free = NULL;
cef_string_userfree_utf16_free_t cef_string_userfree_utf16_free = NULL;
cef_string_utf16_to_lower_t cef_string_utf16_to_lower = NULL;
cef_string_utf16_to_upper_t cef_string_utf16_to_upper = NULL;
cef_get_current_platform_thread_id_t cef_get_current_platform_thread_id = NULL;
cef_get_current_platform_thread_handle_t cef_get_current_platform_thread_handle = NULL;
cef_time_to_timet_t cef_time_to_timet = NULL;
cef_time_from_timet_t cef_time_from_timet = NULL;
cef_time_to_doublet_t cef_time_to_doublet = NULL;
cef_time_from_doublet_t cef_time_from_doublet = NULL;
cef_time_now_t cef_time_now = NULL;
cef_time_delta_t cef_time_delta = NULL;
cef_trace_event_instant_t cef_trace_event_instant = NULL;
cef_trace_event_begin_t cef_trace_event_begin = NULL;
cef_trace_event_end_t cef_trace_event_end = NULL;
cef_trace_counter_t cef_trace_counter = NULL;
cef_trace_counter_id_t cef_trace_counter_id = NULL;
cef_trace_event_async_begin_t cef_trace_event_async_begin = NULL;
cef_trace_event_async_step_into_t cef_trace_event_async_step_into = NULL;
cef_trace_event_async_step_past_t cef_trace_event_async_step_past = NULL;
cef_trace_event_async_end_t cef_trace_event_async_end = NULL;

void initializeCEFFunctions(HMODULE cefModule) {
    #define gcef(X, Y) (X)GetProcAddress(cefModule, Y);
    cef_version_info = gcef(cef_version_info_t, "cef_version_info");
    cef_api_hash = gcef(cef_api_hash_t, "cef_api_hash");
    cef_execute_process = gcef(cef_execute_process_t, "cef_execute_process");
    cef_initialize = gcef(cef_initialize_t, "cef_initialize");
    cef_shutdown = gcef(cef_shutdown_t, "cef_shutdown");
    cef_do_message_loop_work = gcef(cef_do_message_loop_work_t, "cef_do_message_loop_work");
    cef_run_message_loop = gcef(cef_run_message_loop_t, "cef_run_message_loop");
    cef_quit_message_loop = gcef(cef_quit_message_loop_t, "cef_quit_message_loop");
    cef_set_osmodal_loop = gcef(cef_set_osmodal_loop_t, "cef_set_osmodal_loop");
    cef_enable_highdpi_support = gcef(cef_enable_highdpi_support_t, "cef_enable_highdpi_support");
    cef_browser_host_create_browser = gcef(cef_browser_host_create_browser_t, "cef_browser_host_create_browser");
    cef_browser_host_create_browser_sync = gcef(cef_browser_host_create_browser_sync_t, "cef_browser_host_create_browser_sync");
    cef_command_line_create = gcef(cef_command_line_create_t, "cef_command_line_create");
    cef_command_line_get_global = gcef(cef_command_line_get_global_t, "cef_command_line_get_global");
    cef_cookie_manager_get_global_manager = gcef(cef_cookie_manager_get_global_manager_t, "cef_cookie_manager_get_global_manager");
    cef_cookie_manager_get_blocking_manager = gcef(cef_cookie_manager_get_blocking_manager_t, "cef_cookie_manager_get_blocking_manager");
    cef_cookie_manager_create_manager = gcef(cef_cookie_manager_create_manager_t, "cef_cookie_manager_create_manager");
    cef_crash_reporting_enabled = gcef(cef_crash_reporting_enabled_t, "cef_crash_reporting_enabled");
    cef_set_crash_key_value = gcef(cef_set_crash_key_value_t, "cef_set_crash_key_value");
    cef_drag_data_create = gcef(cef_drag_data_create_t, "cef_drag_data_create");
    cef_create_directory = gcef(cef_create_directory_t, "cef_create_directory");
    cef_get_temp_directory = gcef(cef_get_temp_directory_t, "cef_get_temp_directory");
    cef_create_new_temp_directory = gcef(cef_create_new_temp_directory_t, "cef_create_new_temp_directory");
    cef_create_temp_directory_in_directory = gcef(cef_create_temp_directory_in_directory_t, "cef_create_temp_directory_in_directory");
    cef_directory_exists = gcef(cef_directory_exists_t, "cef_directory_exists");
    cef_delete_file = gcef(cef_delete_file_t, "cef_delete_file");
    cef_zip_directory = gcef(cef_zip_directory_t, "cef_zip_directory");
    cef_load_crlsets_file = gcef(cef_load_crlsets_file_t, "cef_load_crlsets_file");
    cef_image_create = gcef(cef_image_create_t, "cef_image_create");
    cef_menu_model_create = gcef(cef_menu_model_create_t, "cef_menu_model_create");
    cef_add_cross_origin_whitelist_entry = gcef(cef_add_cross_origin_whitelist_entry_t, "cef_add_cross_origin_whitelist_entry");
    cef_remove_cross_origin_whitelist_entry = gcef(cef_remove_cross_origin_whitelist_entry_t, "cef_remove_cross_origin_whitelist_entry");
    cef_clear_cross_origin_whitelist = gcef(cef_clear_cross_origin_whitelist_t, "cef_clear_cross_origin_whitelist");
    cef_parse_url = gcef(cef_parse_url_t, "cef_parse_url");
    cef_create_url = gcef(cef_create_url_t, "cef_create_url");
    cef_format_url_for_security_display = gcef(cef_format_url_for_security_display_t, "cef_format_url_for_security_display");
    cef_get_mime_type = gcef(cef_get_mime_type_t, "cef_get_mime_type");
    cef_get_extensions_for_mime_type = gcef(cef_get_extensions_for_mime_type_t, "cef_get_extensions_for_mime_type");
    cef_base64encode = gcef(cef_base64encode_t, "cef_base64encode");
    cef_base64decode = gcef(cef_base64decode_t, "cef_base64decode");
    cef_uriencode = gcef(cef_uriencode_t, "cef_uriencode");
    cef_uridecode = gcef(cef_uridecode_t, "cef_uridecode");
    cef_parse_json = gcef(cef_parse_json_t, "cef_parse_json");
    cef_parse_jsonand_return_error = gcef(cef_parse_jsonand_return_error_t, "cef_parse_jsonand_return_error");
    cef_write_json = gcef(cef_write_json_t, "cef_write_json");
    cef_get_path = gcef(cef_get_path_t, "cef_get_path");
    cef_print_settings_create = gcef(cef_print_settings_create_t, "cef_print_settings_create");
    cef_process_message_create = gcef(cef_process_message_create_t, "cef_process_message_create");
    cef_launch_process = gcef(cef_launch_process_t, "cef_launch_process");
    cef_request_create = gcef(cef_request_create_t, "cef_request_create");
    cef_post_data_create = gcef(cef_post_data_create_t, "cef_post_data_create");
    cef_post_data_element_create = gcef(cef_post_data_element_create_t, "cef_post_data_element_create");
    cef_request_context_get_global_context = gcef(cef_request_context_get_global_context_t, "cef_request_context_get_global_context");
    cef_request_context_create_context = gcef(cef_request_context_create_context_t, "cef_request_context_create_context");
    cef_create_context_shared = gcef(cef_create_context_shared_t, "cef_create_context_shared");
    cef_resource_bundle_get_global = gcef(cef_resource_bundle_get_global_t, "cef_resource_bundle_get_global");
    cef_response_create = gcef(cef_response_create_t, "cef_response_create");
    cef_register_scheme_handler_factory = gcef(cef_register_scheme_handler_factory_t, "cef_register_scheme_handler_factory");
    cef_clear_scheme_handler_factories = gcef(cef_clear_scheme_handler_factories_t, "cef_clear_scheme_handler_factories");
    cef_server_create = gcef(cef_server_create_t, "cef_server_create");
    cef_is_cert_status_error = gcef(cef_is_cert_status_error_t, "cef_is_cert_status_error");
    cef_is_cert_status_minor_error = gcef(cef_is_cert_status_minor_error_t, "cef_is_cert_status_minor_error");
    cef_stream_reader_create_for_file = gcef(cef_stream_reader_create_for_file_t, "cef_stream_reader_create_for_file");
    cef_stream_reader_create_for_data = gcef(cef_stream_reader_create_for_data_t, "cef_stream_reader_create_for_data");
    cef_stream_reader_create_for_handler = gcef(cef_stream_reader_create_for_handler_t, "cef_stream_reader_create_for_handler");
    cef_stream_writer_create_for_file = gcef(cef_stream_writer_create_for_file_t, "cef_stream_writer_create_for_file");
    cef_stream_writer_create_for_handler = gcef(cef_stream_writer_create_for_handler_t, "cef_stream_writer_create_for_handler");
    cef_task_runner_get_for_current_thread = gcef(cef_task_runner_get_for_current_thread_t, "cef_task_runner_get_for_current_thread");
    cef_task_runner_get_for_thread = gcef(cef_task_runner_get_for_thread_t, "cef_task_runner_get_for_thread");
    cef_currently_on = gcef(cef_currently_on_t, "cef_currently_on");
    cef_post_task = gcef(cef_post_task_t, "cef_post_task");
    cef_post_delayed_task = gcef(cef_post_delayed_task_t, "cef_post_delayed_task");
    cef_thread_create = gcef(cef_thread_create_t, "cef_thread_create");
    cef_begin_tracing = gcef(cef_begin_tracing_t, "cef_begin_tracing");
    cef_end_tracing = gcef(cef_end_tracing_t, "cef_end_tracing");
    cef_now_from_system_trace_time = gcef(cef_now_from_system_trace_time_t, "cef_now_from_system_trace_time");
    cef_urlrequest_create = gcef(cef_urlrequest_create_t, "cef_urlrequest_create");
    cef_v8context_get_current_context = gcef(cef_v8context_get_current_context_t, "cef_v8context_get_current_context");
    cef_v8context_get_entered_context = gcef(cef_v8context_get_entered_context_t, "cef_v8context_get_entered_context");
    cef_v8context_in_context = gcef(cef_v8context_in_context_t, "cef_v8context_in_context");
    cef_v8value_create_undefined = gcef(cef_v8value_create_undefined_t, "cef_v8value_create_undefined");
    cef_v8value_create_null = gcef(cef_v8value_create_null_t, "cef_v8value_create_null");
    cef_v8value_create_bool = gcef(cef_v8value_create_bool_t, "cef_v8value_create_bool");
    cef_v8value_create_int = gcef(cef_v8value_create_int_t, "cef_v8value_create_int");
    cef_v8value_create_uint = gcef(cef_v8value_create_uint_t, "cef_v8value_create_uint");
    cef_v8value_create_double = gcef(cef_v8value_create_double_t, "cef_v8value_create_double");
    cef_v8value_create_date = gcef(cef_v8value_create_date_t, "cef_v8value_create_date");
    cef_v8value_create_string = gcef(cef_v8value_create_string_t, "cef_v8value_create_string");
    cef_v8value_create_object = gcef(cef_v8value_create_object_t, "cef_v8value_create_object");
    cef_v8value_create_array = gcef(cef_v8value_create_array_t, "cef_v8value_create_array");
    cef_v8value_create_array_buffer = gcef(cef_v8value_create_array_buffer_t, "cef_v8value_create_array_buffer");
    cef_v8value_create_function = gcef(cef_v8value_create_function_t, "cef_v8value_create_function");
    cef_v8stack_trace_get_current = gcef(cef_v8stack_trace_get_current_t, "cef_v8stack_trace_get_current");
    cef_register_extension = gcef(cef_register_extension_t, "cef_register_extension");
    cef_value_create = gcef(cef_value_create_t, "cef_value_create");
    cef_binary_value_create = gcef(cef_binary_value_create_t, "cef_binary_value_create");
    cef_dictionary_value_create = gcef(cef_dictionary_value_create_t, "cef_dictionary_value_create");
    cef_list_value_create = gcef(cef_list_value_create_t, "cef_list_value_create");
    cef_waitable_event_create = gcef(cef_waitable_event_create_t, "cef_waitable_event_create");
    cef_visit_web_plugin_info = gcef(cef_visit_web_plugin_info_t, "cef_visit_web_plugin_info");
    cef_refresh_web_plugins = gcef(cef_refresh_web_plugins_t, "cef_refresh_web_plugins");
    cef_unregister_internal_web_plugin = gcef(cef_unregister_internal_web_plugin_t, "cef_unregister_internal_web_plugin");
    cef_register_web_plugin_crash = gcef(cef_register_web_plugin_crash_t, "cef_register_web_plugin_crash");
    cef_is_web_plugin_unstable = gcef(cef_is_web_plugin_unstable_t, "cef_is_web_plugin_unstable");
    cef_register_widevine_cdm = gcef(cef_register_widevine_cdm_t, "cef_register_widevine_cdm");
    cef_xml_reader_create = gcef(cef_xml_reader_create_t, "cef_xml_reader_create");
    cef_zip_reader_create = gcef(cef_zip_reader_create_t, "cef_zip_reader_create");
    cef_execute_java_script_with_user_gesture_for_tests = gcef(cef_execute_java_script_with_user_gesture_for_tests_t, "cef_execute_java_script_with_user_gesture_for_tests");
    cef_translator_test_create = gcef(cef_translator_test_create_t, "cef_translator_test_create");
    cef_translator_test_ref_ptr_library_create = gcef(cef_translator_test_ref_ptr_library_create_t, "cef_translator_test_ref_ptr_library_create");
    cef_translator_test_ref_ptr_library_child_create = gcef(cef_translator_test_ref_ptr_library_child_create_t, "cef_translator_test_ref_ptr_library_child_create");
    cef_translator_test_ref_ptr_library_child_child_create = gcef(cef_translator_test_ref_ptr_library_child_child_create_t, "cef_translator_test_ref_ptr_library_child_child_create");
    cef_translator_test_scoped_library_create = gcef(cef_translator_test_scoped_library_create_t, "cef_translator_test_scoped_library_create");
    cef_translator_test_scoped_library_child_create = gcef(cef_translator_test_scoped_library_child_create_t, "cef_translator_test_scoped_library_child_create");
    cef_translator_test_scoped_library_child_child_create = gcef(cef_translator_test_scoped_library_child_child_create_t, "cef_translator_test_scoped_library_child_child_create");
    cef_browser_view_create = gcef(cef_browser_view_create_t, "cef_browser_view_create");
    cef_browser_view_get_for_browser = gcef(cef_browser_view_get_for_browser_t, "cef_browser_view_get_for_browser");
    cef_display_get_primary = gcef(cef_display_get_primary_t, "cef_display_get_primary");
    cef_display_get_nearest_point = gcef(cef_display_get_nearest_point_t, "cef_display_get_nearest_point");
    cef_display_get_matching_bounds = gcef(cef_display_get_matching_bounds_t, "cef_display_get_matching_bounds");
    cef_display_get_count = gcef(cef_display_get_count_t, "cef_display_get_count");
    cef_display_get_alls = gcef(cef_display_get_alls_t, "cef_display_get_alls");
    cef_label_button_create = gcef(cef_label_button_create_t, "cef_label_button_create");
    cef_menu_button_create = gcef(cef_menu_button_create_t, "cef_menu_button_create");
    cef_panel_create = gcef(cef_panel_create_t, "cef_panel_create");
    cef_scroll_view_create = gcef(cef_scroll_view_create_t, "cef_scroll_view_create");
    cef_textfield_create = gcef(cef_textfield_create_t, "cef_textfield_create");
    cef_window_create_top_level = gcef(cef_window_create_top_level_t, "cef_window_create_top_level");
    cef_get_min_log_level = gcef(cef_get_min_log_level_t, "cef_get_min_log_level");
    cef_get_vlog_level = gcef(cef_get_vlog_level_t, "cef_get_vlog_level");
    cef_log = gcef(cef_log_t, "cef_log");
    cef_string_list_alloc = gcef(cef_string_list_alloc_t, "cef_string_list_alloc");
    cef_string_list_size = gcef(cef_string_list_size_t, "cef_string_list_size");
    cef_string_list_value = gcef(cef_string_list_value_t, "cef_string_list_value");
    cef_string_list_append = gcef(cef_string_list_append_t, "cef_string_list_append");
    cef_string_list_clear = gcef(cef_string_list_clear_t, "cef_string_list_clear");
    cef_string_list_free = gcef(cef_string_list_free_t, "cef_string_list_free");
    cef_string_list_copy = gcef(cef_string_list_copy_t, "cef_string_list_copy");
    cef_string_map_alloc = gcef(cef_string_map_alloc_t, "cef_string_map_alloc");
    cef_string_map_size = gcef(cef_string_map_size_t, "cef_string_map_size");
    cef_string_map_find = gcef(cef_string_map_find_t, "cef_string_map_find");
    cef_string_map_key = gcef(cef_string_map_key_t, "cef_string_map_key");
    cef_string_map_value = gcef(cef_string_map_value_t, "cef_string_map_value");
    cef_string_map_append = gcef(cef_string_map_append_t, "cef_string_map_append");
    cef_string_map_clear = gcef(cef_string_map_clear_t, "cef_string_map_clear");
    cef_string_map_free = gcef(cef_string_map_free_t, "cef_string_map_free");
    cef_string_multimap_alloc = gcef(cef_string_multimap_alloc_t, "cef_string_multimap_alloc");
    cef_string_multimap_size = gcef(cef_string_multimap_size_t, "cef_string_multimap_size");
    cef_string_multimap_find_count = gcef(cef_string_multimap_find_count_t, "cef_string_multimap_find_count");
    cef_string_multimap_enumerate = gcef(cef_string_multimap_enumerate_t, "cef_string_multimap_enumerate");
    cef_string_multimap_key = gcef(cef_string_multimap_key_t, "cef_string_multimap_key");
    cef_string_multimap_value = gcef(cef_string_multimap_value_t, "cef_string_multimap_value");
    cef_string_multimap_append = gcef(cef_string_multimap_append_t, "cef_string_multimap_append");
    cef_string_multimap_clear = gcef(cef_string_multimap_clear_t, "cef_string_multimap_clear");
    cef_string_multimap_free = gcef(cef_string_multimap_free_t, "cef_string_multimap_free");
    cef_string_wide_set = gcef(cef_string_wide_set_t, "cef_string_wide_set");
    cef_string_utf8_set = gcef(cef_string_utf8_set_t, "cef_string_utf8_set");
    cef_string_utf16_set = gcef(cef_string_utf16_set_t, "cef_string_utf16_set");
    cef_string_wide_clear = gcef(cef_string_wide_clear_t, "cef_string_wide_clear");
    cef_string_utf8_clear = gcef(cef_string_utf8_clear_t, "cef_string_utf8_clear");
    cef_string_utf16_clear = gcef(cef_string_utf16_clear_t, "cef_string_utf16_clear");
    cef_string_wide_cmp = gcef(cef_string_wide_cmp_t, "cef_string_wide_cmp");
    cef_string_utf8_cmp = gcef(cef_string_utf8_cmp_t, "cef_string_utf8_cmp");
    cef_string_utf16_cmp = gcef(cef_string_utf16_cmp_t, "cef_string_utf16_cmp");
    cef_string_wide_to_utf8 = gcef(cef_string_wide_to_utf8_t, "cef_string_wide_to_utf8");
    cef_string_utf8_to_wide = gcef(cef_string_utf8_to_wide_t, "cef_string_utf8_to_wide");
    cef_string_wide_to_utf16 = gcef(cef_string_wide_to_utf16_t, "cef_string_wide_to_utf16");
    cef_string_utf16_to_wide = gcef(cef_string_utf16_to_wide_t, "cef_string_utf16_to_wide");
    cef_string_utf8_to_utf16 = gcef(cef_string_utf8_to_utf16_t, "cef_string_utf8_to_utf16");
    cef_string_utf16_to_utf8 = gcef(cef_string_utf16_to_utf8_t, "cef_string_utf16_to_utf8");
    cef_string_ascii_to_wide = gcef(cef_string_ascii_to_wide_t, "cef_string_ascii_to_wide");
    cef_string_ascii_to_utf16 = gcef(cef_string_ascii_to_utf16_t, "cef_string_ascii_to_utf16");
    cef_string_userfree_wide_alloc = gcef(cef_string_userfree_wide_alloc_t, "cef_string_userfree_wide_alloc");
    cef_string_userfree_utf8_alloc = gcef(cef_string_userfree_utf8_alloc_t, "cef_string_userfree_utf8_alloc");
    cef_string_userfree_utf16_alloc = gcef(cef_string_userfree_utf16_alloc_t, "cef_string_userfree_utf16_alloc");
    cef_string_userfree_wide_free = gcef(cef_string_userfree_wide_free_t, "cef_string_userfree_wide_free");
    cef_string_userfree_utf8_free = gcef(cef_string_userfree_utf8_free_t, "cef_string_userfree_utf8_free");
    cef_string_userfree_utf16_free = gcef(cef_string_userfree_utf16_free_t, "cef_string_userfree_utf16_free");
    cef_string_utf16_to_lower = gcef(cef_string_utf16_to_lower_t, "cef_string_utf16_to_lower");
    cef_string_utf16_to_upper = gcef(cef_string_utf16_to_upper_t, "cef_string_utf16_to_upper");
    cef_get_current_platform_thread_id = gcef(cef_get_current_platform_thread_id_t, "cef_get_current_platform_thread_id");
    cef_get_current_platform_thread_handle = gcef(cef_get_current_platform_thread_handle_t, "cef_get_current_platform_thread_handle");
    cef_time_to_timet = gcef(cef_time_to_timet_t, "cef_time_to_timet");
    cef_time_from_timet = gcef(cef_time_from_timet_t, "cef_time_from_timet");
    cef_time_to_doublet = gcef(cef_time_to_doublet_t, "cef_time_to_doublet");
    cef_time_from_doublet = gcef(cef_time_from_doublet_t, "cef_time_from_doublet");
    cef_time_now = gcef(cef_time_now_t, "cef_time_now");
    cef_time_delta = gcef(cef_time_delta_t, "cef_time_delta");
    cef_trace_event_instant = gcef(cef_trace_event_instant_t, "cef_trace_event_instant");
    cef_trace_event_begin = gcef(cef_trace_event_begin_t, "cef_trace_event_begin");
    cef_trace_event_end = gcef(cef_trace_event_end_t, "cef_trace_event_end");
    cef_trace_counter = gcef(cef_trace_counter_t, "cef_trace_counter");
    cef_trace_counter_id = gcef(cef_trace_counter_id_t, "cef_trace_counter_id");
    cef_trace_event_async_begin = gcef(cef_trace_event_async_begin_t, "cef_trace_event_async_begin");
    cef_trace_event_async_step_into = gcef(cef_trace_event_async_step_into_t, "cef_trace_event_async_step_into");
    cef_trace_event_async_step_past = gcef(cef_trace_event_async_step_past_t, "cef_trace_event_async_step_past");
    cef_trace_event_async_end = gcef(cef_trace_event_async_end_t, "cef_trace_event_async_end");
}
#endif // #ifdef DYNAMIC_CEF
